"""Decision contracts for FactoryOS Autonomous Guardian System."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field


class DecisionActionType(str, Enum):
    RUN_WORKER = "RUN_WORKER"
    VALIDATE_CONTRACT = "VALIDATE_CONTRACT"
    REGENERATE_TARGET = "REGENERATE_TARGET"
    REPLAN = "REPLAN"
    ESCALATE = "ESCALATE"
    COMPLETE = "COMPLETE"
    TERMINATE_FAIL = "TERMINATE_FAIL"


class ReasonCategory(str, Enum):
    INITIAL_PLANNING = "INITIAL_PLANNING"
    REQUIRED_VALIDATION = "REQUIRED_VALIDATION"
    WORKER_DEPENDENCY = "WORKER_DEPENDENCY"
    RECOVERY_ATTEMPT = "RECOVERY_ATTEMPT"
    POLICY_COMPLIANCE = "POLICY_COMPLIANCE"
    OBJECTIVE_SATISFIED = "OBJECTIVE_SATISFIED"
    FATAL_FAILURE = "FATAL_FAILURE"


class GuardianDecisionProposal(BaseModel):
    """Raw proposal generated by a reasoning engine (LLM or Deterministic)."""

    model_config = ConfigDict(extra="forbid")

    action_type: DecisionActionType = Field(...)
    target_capability: Optional[str] = Field(default=None)
    target_worker: Optional[str] = Field(default=None)
    reason_category: ReasonCategory = Field(...)
    reasoning_summary: str = Field(..., min_length=5)
    expected_outcome: str = Field(..., min_length=5)
    fallback_action: Optional[str] = Field(default=None)
    parameters: Dict[str, Any] = Field(default_factory=dict)

    candidate_actions: List[str] = Field(default_factory=list)
    rejected_actions: List[Dict[str, str]] = Field(default_factory=list)


class GuardianDecision(BaseModel):
    """Authoritative, validated decision record accepted by the Guardian Action Gate."""

    model_config = ConfigDict(extra="forbid")

    decision_id: UUID = Field(default_factory=uuid4)
    execution_id: UUID = Field(...)
    floor_id: str = Field(...)

    objective: str = Field(...)
    action_type: DecisionActionType = Field(...)

    target_capability: Optional[str] = Field(default=None)
    target_worker: Optional[str] = Field(default=None)

    observation: Optional[str] = Field(default=None)
    candidate_actions: List[str] = Field(default_factory=list)
    rejected_actions: List[Dict[str, str]] = Field(default_factory=list)
    selected_action: str = Field(default="")
    selection_reason: str = Field(default="")

    reason_category: ReasonCategory = Field(...)
    reasoning_summary: str = Field(...)

    evidence_ids: List[str] = Field(default_factory=list)
    policy_ids: List[str] = Field(default_factory=list)
    policy_checks: List[Dict[str, Any]] = Field(default_factory=list)

    confidence: Optional[float] = Field(default=1.0, ge=0.0, le=1.0)
    expected_outcome: str = Field(...)
    fallback_action: Optional[str] = Field(default=None)
    parameters: Dict[str, Any] = Field(default_factory=dict)

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
