/**
 * FactoryOS Frontier v2 — Overseer Expression Presets & Visual Constants
 * Defines original robotic face geometry presets and darker FactoryOS industrial palette.
 */

import type { OverseerIntent, FaceParameters } from "./OverseerPresenceContracts";

export const OVERSEER_EXPRESSION_PRESETS: Record<OverseerIntent, FaceParameters> = {
  IDLE: {
    eye: {
      openness: 0.85,
      width: 1.0,
      height: 1.0,
      pupilScale: 1.0,
      gazeX: 0.0,
      gazeY: 0.0,
      eyebrowAngle: 0,
      blinkAmount: 0.0,
      softness: 0.3,
    },
    mouthCurve: 0.0,
    mouthOpenness: 0.0,
    headTilt: 0,
    faceScale: 1.0,
    glowIntensity: 0.45,
    accentColor: "#0A84FF", // Darker FactoryOS Primary Blue
    pulseFrequency: 0.5,
  },

  GREETING: {
    eye: {
      openness: 0.95,
      width: 1.05,
      height: 1.05,
      pupilScale: 1.15,
      gazeX: 0.0,
      gazeY: -0.05,
      eyebrowAngle: 3,
      blinkAmount: 0.0,
      softness: 0.5,
    },
    mouthCurve: 0.5,
    mouthOpenness: 0.08,
    headTilt: -2,
    faceScale: 1.02,
    glowIntensity: 0.6,
    accentColor: "#19BFFF", // Electric Accent
    pulseFrequency: 0.8,
  },

  LISTENING: {
    eye: {
      openness: 0.95,
      width: 1.02,
      height: 1.02,
      pupilScale: 1.2,
      gazeX: 0.0,
      gazeY: -0.05,
      eyebrowAngle: 2,
      blinkAmount: 0.0,
      softness: 0.4,
    },
    mouthCurve: 0.1,
    mouthOpenness: 0.04,
    headTilt: 3,
    faceScale: 1.03,
    glowIntensity: 0.7,
    accentColor: "#0A84FF",
    pulseFrequency: 1.2,
  },

  OBSERVING: {
    eye: {
      openness: 0.8,
      width: 1.0,
      height: 0.95,
      pupilScale: 0.9,
      gazeX: 0.2,
      gazeY: 0.1,
      eyebrowAngle: 2,
      blinkAmount: 0.0,
      softness: 0.3,
    },
    mouthCurve: 0.0,
    mouthOpenness: 0.0,
    headTilt: 0,
    faceScale: 1.0,
    glowIntensity: 0.5,
    accentColor: "#0866C6", // Focused Navy Blue
    pulseFrequency: 0.6,
  },

  THINKING: {
    eye: {
      openness: 0.75,
      width: 0.95,
      height: 0.9,
      pupilScale: 0.85,
      gazeX: 0.3,
      gazeY: -0.2,
      eyebrowAngle: -4,
      blinkAmount: 0.0,
      softness: 0.4,
    },
    mouthCurve: -0.1,
    mouthOpenness: 0.0,
    headTilt: -4,
    faceScale: 0.98,
    glowIntensity: 0.65,
    accentColor: "#6366F1", // Indigo Cognitive
    pulseFrequency: 1.0,
  },

  DEEP_THINKING: {
    eye: {
      openness: 0.65,
      width: 0.9,
      height: 0.85,
      pupilScale: 0.75,
      gazeX: 0.0,
      gazeY: -0.3,
      eyebrowAngle: -6,
      blinkAmount: 0.0,
      softness: 0.6,
    },
    mouthCurve: -0.2,
    mouthOpenness: 0.0,
    headTilt: 0,
    faceScale: 0.96,
    glowIntensity: 0.8,
    accentColor: "#4F46E5", // Deep Indigo
    pulseFrequency: 1.5,
  },

  CURIOUS: {
    eye: {
      openness: 0.95,
      width: 1.08,
      height: 1.08,
      pupilScale: 1.25,
      gazeX: -0.2,
      gazeY: -0.1,
      eyebrowAngle: 6,
      blinkAmount: 0.0,
      softness: 0.5,
    },
    mouthCurve: 0.2,
    mouthOpenness: 0.05,
    headTilt: 6,
    faceScale: 1.02,
    glowIntensity: 0.6,
    accentColor: "#19BFFF",
    pulseFrequency: 0.9,
  },

  CONCERNED: {
    eye: {
      openness: 0.75,
      width: 1.0,
      height: 0.9,
      pupilScale: 0.9,
      gazeX: 0.0,
      gazeY: 0.1,
      eyebrowAngle: -9,
      blinkAmount: 0.0,
      softness: 0.5,
    },
    mouthCurve: -0.3,
    mouthOpenness: 0.0,
    headTilt: -3,
    faceScale: 0.98,
    glowIntensity: 0.7,
    accentColor: "#F59E0B", // Warm Industrial Amber
    pulseFrequency: 1.1,
  },

  WARNING: {
    eye: {
      openness: 0.85,
      width: 1.05,
      height: 0.95,
      pupilScale: 0.95,
      gazeX: 0.0,
      gazeY: 0.0,
      eyebrowAngle: -12,
      blinkAmount: 0.0,
      softness: 0.3,
    },
    mouthCurve: -0.4,
    mouthOpenness: 0.0,
    headTilt: 0,
    faceScale: 1.0,
    glowIntensity: 0.85,
    accentColor: "#D97706", // Alert Amber
    pulseFrequency: 1.8,
  },

  CRITICAL: {
    eye: {
      openness: 0.9,
      width: 1.1,
      height: 0.85,
      pupilScale: 0.7,
      gazeX: 0.0,
      gazeY: 0.0,
      eyebrowAngle: -16,
      blinkAmount: 0.0,
      softness: 0.2,
    },
    mouthCurve: -0.6,
    mouthOpenness: 0.0,
    headTilt: 0,
    faceScale: 1.04,
    glowIntensity: 1.0,
    accentColor: "#EF4444", // Controlled Crimson Red
    pulseFrequency: 2.5,
  },

  RECOVERING: {
    eye: {
      openness: 0.8,
      width: 1.0,
      height: 0.95,
      pupilScale: 1.0,
      gazeX: 0.0,
      gazeY: 0.0,
      eyebrowAngle: -3,
      blinkAmount: 0.0,
      softness: 0.6,
    },
    mouthCurve: 0.1,
    mouthOpenness: 0.0,
    headTilt: 2,
    faceScale: 0.99,
    glowIntensity: 0.6,
    accentColor: "#0284C7", // Restorative Cyan/Blue
    pulseFrequency: 0.7,
  },

  VERIFYING: {
    eye: {
      openness: 0.85,
      width: 1.02,
      height: 1.0,
      pupilScale: 0.95,
      gazeX: 0.1,
      gazeY: -0.1,
      eyebrowAngle: 1,
      blinkAmount: 0.0,
      softness: 0.3,
    },
    mouthCurve: 0.0,
    mouthOpenness: 0.0,
    headTilt: -1,
    faceScale: 1.0,
    glowIntensity: 0.7,
    accentColor: "#38BDF8", // Ice Blue Inspection
    pulseFrequency: 1.0,
  },

  SUCCESS: {
    eye: {
      openness: 0.95,
      width: 1.1,
      height: 1.1,
      pupilScale: 1.2,
      gazeX: 0.0,
      gazeY: -0.05,
      eyebrowAngle: 5,
      blinkAmount: 0.0,
      softness: 0.6,
    },
    mouthCurve: 0.7,
    mouthOpenness: 0.05,
    headTilt: -2,
    faceScale: 1.05,
    glowIntensity: 0.85,
    accentColor: "#10B981", // Restrained Emerald
    pulseFrequency: 0.6,
  },

  PROUD: {
    eye: {
      openness: 0.9,
      width: 1.08,
      height: 1.05,
      pupilScale: 1.1,
      gazeX: 0.0,
      gazeY: -0.1,
      eyebrowAngle: 4,
      blinkAmount: 0.0,
      softness: 0.5,
    },
    mouthCurve: 0.6,
    mouthOpenness: 0.0,
    headTilt: 3,
    faceScale: 1.03,
    glowIntensity: 0.8,
    accentColor: "#10B981",
    pulseFrequency: 0.5,
  },

  WAITING: {
    eye: {
      openness: 0.7,
      width: 0.95,
      height: 0.95,
      pupilScale: 0.95,
      gazeX: 0.1,
      gazeY: 0.1,
      eyebrowAngle: 0,
      blinkAmount: 0.0,
      softness: 0.3,
    },
    mouthCurve: 0.0,
    mouthOpenness: 0.0,
    headTilt: 1,
    faceScale: 0.98,
    glowIntensity: 0.35,
    accentColor: "#0A84FF",
    pulseFrequency: 0.4,
  },

  FAREWELL: {
    eye: {
      openness: 0.8,
      width: 1.0,
      height: 1.0,
      pupilScale: 1.0,
      gazeX: 0.0,
      gazeY: 0.0,
      eyebrowAngle: 2,
      blinkAmount: 0.0,
      softness: 0.4,
    },
    mouthCurve: 0.3,
    mouthOpenness: 0.0,
    headTilt: -2,
    faceScale: 1.0,
    glowIntensity: 0.5,
    accentColor: "#0A84FF",
    pulseFrequency: 0.5,
  },

  SLEEP: {
    eye: {
      openness: 0.05,
      width: 0.85,
      height: 0.85,
      pupilScale: 0.8,
      gazeX: 0.0,
      gazeY: 0.2,
      eyebrowAngle: 0,
      blinkAmount: 0.95,
      softness: 0.2,
    },
    mouthCurve: 0.0,
    mouthOpenness: 0.0,
    headTilt: 4,
    faceScale: 0.95,
    glowIntensity: 0.15,
    accentColor: "#1E3A8A", // Deep Slate Blue
    pulseFrequency: 0.2,
  },
};
